dreamweaver/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, re_path, include

from sar.views import home


admin.AdminSite.site_title = settings.SITE_NAME
admin.AdminSite.site_header = '%s 管理' % settings.SITE_NAME

urlpatterns = [
    path('', home, name='home'),
    path('', include('account.urls')),
    path('sar/', include('sar.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    # Server statics and uploaded media
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

    # debug_toolbar
    urlpatterns.extend([
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ])

sar/urls.py
from django.urls import path

from . import views

app_name = 'sar'
urlpatterns = [
    path('<table_id>/', views.sar, name='table'),
]

sar/models.py
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django_extensions.db.fields.json import JSONField

User = get_user_model()


class Table(models.Model):
    name = models.CharField('表名', max_length=64)
    price = models.DecimalField('价格', max_digits=10, decimal_places=2, null=True)

    def has_view_permission(self, request, obj=None):
        if request.user.is_superuser:
            return True

        if Pay.objects.filter(user=request.user).filter(table=self).exists():
            return True

        return False

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '表格'
        verbose_name_plural = verbose_name


class TableHeader(models.Model):
    table = models.ForeignKey(Table, verbose_name="表格", on_delete=models.CASCADE)
    name = models.CharField('字段名', max_length=64)
    data = JSONField('数据')
    rank = models.SmallIntegerField('优先级', default=0)

    def clean(self):
        if not isinstance(self.data, list):
            raise ValidationError('data is not a list')

    def __str__(self):
        return "%s --> %s" % (self.table.name, self.name)

    class Meta:
        verbose_name = '表头'
        verbose_name_plural = verbose_name


class Result(models.Model):
    table = models.ForeignKey(Table, verbose_name="表格", on_delete=models.CASCADE)
    label = models.CharField(max_length=64, null=True)
    value = models.IntegerField('值')
    computed_value = JSONField('计算值', null=True, editable=False)

    def __str__(self):
        return "%s: %s" % (self.label, self.value)

    def save(self, *args, **kwargs):
        if not self.computed_value:
            self.make_computed_value()
        super().save(*args, **kwargs)

    def make_computed_value(self):
        computed_value = {}
        headers = self.table.tableheader_set.all()
        for header in headers:
            assert isinstance(header.data, list)
            for index in range(len(header.data)):
                assert isinstance(header.data[index], list)
                if self.value in header.data[index]:
                    computed_value[header.id] = index

        self.computed_value = computed_value

    class Meta:
        verbose_name = '结果'
        verbose_name_plural = verbose_name


class CrawlHistory(models.Model):
    # crawl https://datachart.500.com/ssq/history/history.shtml

    HEADERS = ['date_code', 'red_1', 'red_2', 'red_3', 'red_4', 'red_5', 'red_6',
               'blue', 'happy_sunday', 'jackpot_bonuses', 'first_prize_num', 'first_prize_bonus',
               'second_prize_num', 'second_prize_bonus', 'total_bet', 'lottery_date']

    HEADER_LABELS = {
        'date_code': '期号',
        'red_1': '红1',
        'red_2': '红2',
        'red_3': '红3',
        'red_4': '红4',
        'red_5': '红5',
        'red_6': '红6',
        'blue': '蓝球',
        'happy_sunday': '快乐星期天',
        'jackpot_bonuses': '奖池奖金(元)',
        'first_prize_num': '一等奖注数',
        'first_prize_bonus': '一等奖奖金(元)',
        'second_prize_num': '二等奖注数',
        'second_prize_bonus': '二等奖奖金(元)',
        'total_bet': '总投注额(元)',
        'lottery_date': '开奖日期'
        }

    crawled_at = models.DateTimeField('爬取时间', null=True, editable=False)
    status = models.CharField('爬取状态', max_length=32, null=True, editable=False)
    data = JSONField('数据', null=True, editable=False)


class Pay(models.Model):
    user = models.ForeignKey(User, verbose_name="用户", on_delete=models.CASCADE)
    table = models.ForeignKey(Table, verbose_name="表格", on_delete=models.CASCADE)
    price = models.DecimalField('价格', max_digits=10, decimal_places=2)
    created_at = models.DateTimeField('支付时间', editable=False, default=timezone.now)

    class Meta:
        verbose_name = '支付记录'
        verbose_name_plural = verbose_name

    def __str__(self):
        return "%s: ￥%s" % (self.created_at, self.price)


class Option(models.Model):
    name = models.CharField('项目', max_length=200, unique=True, editable=False)
    slug = models.CharField('Slug', max_length=200, unique=True, editable=False)
    value = models.CharField('值', max_length=250, null=True, blank=True)
    enable = models.BooleanField(default=True)

    class Meta:
        verbose_name = '选项'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

sar/views.py
import requests
from bs4 import BeautifulSoup
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from .models import CrawlHistory, Table


@login_required
def sar(request, table_id):
    table = get_object_or_404(Table, pk=table_id)

    if not table.has_view_permission(request):
        return HttpResponseForbidden()

    result_queryset = table.result_set.all()
    paginator = Paginator(result_queryset, settings.PAGINATE_BY)

    page = request.GET.get('page')

    if page:
        pagination = paginator.get_page(page)
        results = pagination
    else:
        pagination = paginator.get_page(paginator.num_pages)

        if result_queryset.count() > settings.PAGINATE_BY:
            # 选取最后几个再反转
            results = list(result_queryset.order_by('-id')[:settings.PAGINATE_BY])[::-1]
        else:
            results = result_queryset

    headers = table.tableheader_set.all()

    return render(request, 'sar/table.html', {
        "headers": headers,
        "results": results,
        "pagination": pagination,
        "table": table,
    })


def home(request):
    today = timezone.now()
    shuangseqiu_data = []
    crawl_history = CrawlHistory.objects.filter(crawled_at__date=today.date()).first()

    if crawl_history is None:
        r = requests.get('https://datachart.500.com/ssq/history/history.shtml')

        if r.status_code == requests.codes.ok:
            soup = BeautifulSoup(r.text)
            trs = soup.find_all('tr', class_='t_tr1')

            for tr in trs:
                tds = tr.find_all('td')
                values = [td.text for td in tds]
                data = dict(zip(CrawlHistory.HEADERS, values))
                shuangseqiu_data.append(data)

            if shuangseqiu_data:
                crawl_history = CrawlHistory(crawled_at=today, status='success', data=shuangseqiu_data)
                crawl_history.save()

    else:
        shuangseqiu_data = crawl_history.data

    return render(request, 'sar/home.html', {
        'tables': Table.objects.all(),
        "shuangseqiu_data": shuangseqiu_data,
        'headers': CrawlHistory.HEADERS,
        'header_labels': CrawlHistory.HEADER_LABELS
    })

templates/sar/home.html
{% extends '_layout/base.html' %}
{% load static %}
{% load sar_base %}
{% block title %}首页{% endblock %}

{% block content %}
    <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
        <img class="mr-3" src="{% static 'img/logo.png' %}" alt="" width="48" height="48">
        <div class="lh-100">
            <h6 class="mb-0 text-white lh-100">{{ site_name }}</h6>
            <small>Since 2017</small>
        </div>
    </div>
    <div class="text-center">
        <h2 style="color: red">{{ qrcode_title }}</h2>
        <div class="qrcodes">
            {% for table in tables %}
                <div class="card qrcode-card" style="width: 130px">
                    <img class="card-img-top" src="{% static 'img/ma.png' %}" alt="" width="128" height="128"/>
                    <div class="card-body">
                        <a class="qrcode-link" href="{% url 'sar:table' table.id %}" title="{{ table.name }}">
                            {{ table.name }} <span class="price">￥{{ table.price }}元</span>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">双色球开奖记录</h6>
        {% if shuangseqiu_data|length == 0 %}
            <figure class="figure">
                <img src="http://ww3.sinaimg.cn/large/85cc5ccbgy1fo5gordjvzj20m80m875r.jpg"
                     class="figure-img img-fluid rounded" alt="" width="300">
                <figcaption class="figure-caption text-right">获取数据失败.</figcaption>
            </figure>
        {% else %}
            <table class="table table-striped table-bordered table-sm">
                <thead class="thead-dark">
                <tr>
                    {% for label in headers %}
                        <th>{{ header_labels|get_item:label }}</th>
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for data in shuangseqiu_data %}
                    <tr>
                        {% for label in headers %}
                            <td>{{ data|get_item:label }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}

templates/sar/table.html
{% extends '_layout/base.html' %}
{% load static %}
{% load sar_base %}
{% block title %}{{ table.name }}{% endblock %}

{% block content %}
    <div class="my-3 p-3 bg-white rounded box-shadow">
        <button id="show-line-button" class="btn btn-light" style="margin-bottom: 12px">隐藏趋势</button>
        <div id="content" style="width:100%;">
            <table class="sar-table table table-sm table-bordered table-hover text-center">
                <thead>
                <tr>
                    <th class="label-title" scope="col" rowspan=2>{{ table.name }}</th>
                    {% for header in headers %}
                        <th class="sar-td-1" scope="col" colspan={{ header.data | length }}>{{ header.name }}</th>
                    {% endfor %}
                </tr>
                <tr>
                    {% for header in headers %}
                        {% for foo in  header.data %}
                            <th scope="col" class="sar-td sar-td-{{ forloop.counter }}">{{ forloop.counter }}</th>
                        {% endfor %}
                    {% endfor %}
                </tr>
                </thead>
                <tbody>
                {% for result in results %}
                    <tr id="result-{{ forloop.counter0 }}">
                        <td class="label-title">{{ result.label }}</td>
                        {% for header in headers %}
                            {% for foo in header.data %}
                                {% if result.computed_value|get_item:header.id == forloop.counter0 %}
                                    <td class="sar-td sar-td-{{ forloop.counter }}">
                                        <span class="point point-{{ forloop.parentloop.counter0 }}">●</span>
                                    </td>
                                {% else %}
                                    <td class="sar-td sar-td-{{ forloop.counter }}"></td>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    </tr>
                {% endfor %}
                <tr id="result-next">
                    <td class="tooltip-toggle label-title">下一期</td>
                    {% for header in headers %}
                        {% for foo in header.data %}
                            <td class="tooltip-toggle sar-td sar-td-{{ forloop.counter }}"
                                data-toggle="tooltip" data-html="true" data-placement="bottom"
                                title="<em>下期预测：</em> <u>{{ foo }}</u>"></td>
                        {% endfor %}
                    {% endfor %}
                </tr>
                </tbody>
            </table>
            <canvas id="my-canvas"></canvas>
        </div>
    </div>

    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if pagination.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1"><span class="meta-nav">&laquo;</span> First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ pagination.previous_page_number }}">
                        Previous
                    </a>
                </li>
            {% endif %}

            <li class="page-item disabled">
                <span class="page-link">Page {{ pagination.number }} of {{ pagination.paginator.num_pages }}.</span>
            </li>

            {% if pagination.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ pagination.next_page_number }}">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <!-- pagination.paginator.num_pages -->
                    <a class="page-link" href="{% url 'sar:table' table.id %}">
                        Last <span class="meta-nav">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

{% block scripts %}
    <script>
        $(function () {
            $('td.tooltip-toggle').tooltip();

            $(window).resize(function () {
                drawLines({{ headers | length }}, {{ results | length }});
                resetTable();
            });

            $('#show-line-button').click(function () {
                if ($(this).text() === '隐藏趋势') {
                    $('#my-canvas').css('z-index', -1);
                    $(this).text('查看趋势');
                } else {
                    $('#my-canvas').css('z-index', 1);
                    $(this).text('隐藏趋势');
                }
            });

            drawLines({{ headers | length }}, {{ results | length }});
            resetTable();
            FixedHead();
            fixedCol();
        });
    </script>
{% endblock %}