account/urls.py
from django.urls import path

from . import views
from .forms import LoginForm

app_name = "account"  # noqa

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login', kwargs={'authentication_form': LoginForm}),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout')
]

dreamweaver/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, re_path, include

from sar.views import home


admin.AdminSite.site_title = settings.SITE_NAME
admin.AdminSite.site_header = '%s 管理' % settings.SITE_NAME

urlpatterns = [
    path('', home, name='home'),
    path('', include('account.urls')),
    path('sar/', include('sar.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    # Server statics and uploaded media
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

    # debug_toolbar
    urlpatterns.extend([
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ])

sar/urls.py
from django.urls import path

from . import views

app_name = 'sar'
urlpatterns = [
    path('<table_id>/', views.sar, name='table'),
]

templates/_layout/base.html
{% load sar_base static %}<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{{ site_description }}">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <title>{% block title %}{% endblock %} | {{ site_name }}</title>

    <link href="{% mix 'css' 'style.min.css' %}" rel="stylesheet">
    {% block header_css %}{% endblock %}
    {% block header_js %}{% endblock %}
</head>

<body class="bg-light">
{% include '_layout/nav.html' %}

<main id="main" class="container">
    {% block content %}{% endblock %}
</main>

{% include '_layout/footer.html' %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% mix 'js' 'app.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

templates/_layout/base_account.html
{% load static sar_base %}<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ site_description }}">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <title>{{ site_name }} | {{ site_description }}</title>
    <link href="{% mix 'css' 'style.min.css' %}" rel="stylesheet">
</head>

<body class="account">
{% block breadcrumbs %}{% endblock %}
{% block content %}{% endblock %}
</body>
</html>

templates/_layout/footer.html
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>&copy; {{ site_name }}, 风险提示：{{ site_name }} 里任何用户或者嘉宾的发言，都有其特定立场，投资决策需要建立在独立思考之上!</p>
        <p>New to {{ site_name }}? <a href="{% url 'account:register' %}">Register</a>.
        </p>
    </div>
</footer>

templates/_layout/nav.html
<nav class="navbar navbar-expand-md navbar-light bg-light border-bottom box-shadow">
    <a class="navbar-brand" href="/">{{ site_name }}</a>
    <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse offcanvas-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">主页 <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="user-settings"
                       data-toggle="dropdown">{{ user.username }}</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-settings">
                        {% if user.is_superuser %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}">后台管理</a>
                            <div class="dropdown-divider"></div>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'account:logout' %}">登出</a>
                    </div>
                </li>
            </ul>
        {% else %}
            <a class="btn btn-default" href="{% url 'account:register' %}">注册</a>
            <a class="btn btn-outline-primary" href="{% url 'account:login' %}">登录</a>
        {% endif %}
    </div>
</nav>